@baseUrl = http://localhost:1337
@token = a2aa06eefd386508fa91682b1c7f4e98bbefcf2c1172530e8869c3dac6f77d7e59524e3cbc0eaca58d5276d0cf965327b36e360752eb7b96e3371c6fc68e772311dcd822cd388e91ce863b649208af7ce4b285f5346142c029476fe4a022eafc5dd87a9e4ee933ba1a350607dc0e0f8116b562b1adfa96eb7ec63ccd4d114c61
### Obtener todos los libros
GET {{baseUrl}}/api/books?populate=*
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/api/users/1?populate=*
Authorization: Bearer {{token}}

### Crear un comentario de libro
PUT {{baseUrl}}/api/books/ohs6kpcjgvczvv4j8k4jii6e
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "data": {
        "totalViews": 5
    }
}

### Crear un nuevo libro
POST {{baseUrl}}/api/books
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "data": {
        "title": "example title",
        "author": "example author",
        "description": "example description",
        "bookStatus": "ongoing",
        "language": "ES",
        "type": "manhwa",
        "users_permissions_user": "wpbjm5x4m2xlbs1exk0u2w6t",
        "coverImage": 13
    }
}